//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthlonConsultancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantpartnerBBAView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string AppCVUpload { get; set; }
        public string DOB { get; set; }
        public string ReferBy { get; set; }
        public string Industry { get; set; }
        public string GName { get; set; }
        public string GStatus { get; set; }
        public string FirmName { get; set; }
        public string TotalExp { get; set; }
        public string Experties { get; set; }
        public string ExpCity { get; set; }
        public string JoinDate { get; set; }
        public string LeaveDateOPW { get; set; }
        public string RelevantIndustry { get; set; }
        public string Country { get; set; }
    }
}
