//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthlonConsultancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantBBAView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Contactno { get; set; }
        public string Age { get; set; }
        public string ReferBy { get; set; }
        public string Schoolname { get; set; }
        public string Collegename { get; set; }
        public string AcadQual { get; set; }
        public string AdvAcadQual { get; set; }
        public string GName { get; set; }
        public string GPA { get; set; }
        public string University { get; set; }
        public string MajorSubjects { get; set; }
        public string OtherSubjects { get; set; }
        public string Extracuri { get; set; }
        public string Achivements { get; set; }
        public string ExpStatus { get; set; }
        public string NOYExperience { get; set; }
        public string OrgName { get; set; }
        public string Agree { get; set; }
        public string UploadCV { get; set; }
        public Nullable<int> Applicantid { get; set; }
    }
}
