//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthlonConsultancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizationscv
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string OrgCVUpload { get; set; }
        public string City { get; set; }
        public string DOB { get; set; }
        public string ReferBy { get; set; }
        public string QName { get; set; }
        public string QStatus { get; set; }
        public string DOQ { get; set; }
        public string EducationBoard { get; set; }
        public string NOPL { get; set; }
        public string GName { get; set; }
        public string GPA { get; set; }
        public string University { get; set; }
        public string MajorSubject { get; set; }
        public string OtherSubject { get; set; }
        public string ExpStatus { get; set; }
        public string NOYMExperience { get; set; }
        public string OrgName { get; set; }
    }
}
