//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EthlonConsultancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostJob
    {
        public int Id { get; set; }
        public string OrgName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string QualRequirements { get; set; }
    }
}
